---
- name: docker_preconfig
  hosts: docker_host
  tasks:
    - name: Установка Docker
      block:

        - name: Добавляем universe
          apt_repository:
            repo: "deb http://deb.debian.org/debian/ {{ ansible_distribution_release }} universe"
            state: present

        - name: "Remove old package"
          apt:
            name:
              - docker
              - docker-engine
              - docker.io
              - containerd
              - runc
            state: absent

        - name: "Install additional package for Docker"
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update_cache: yes

        - name: "Add an Apt signing key to a specific keyring file"
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/debian/gpg

        - name: "Установка стабильного репа Docker"
          ansible.builtin.apt_repository:
            repo: "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
                    $(lsb_release -cs) stable"
            state: present
            update_cache: yes
            filename: docker

        - name: "Install Docker"
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            update_cache: yes

        - name: Restart service Docker
          ansible.builtin.service:
            name: docker
            state: restarted
            enabled: yes
      become: yes

    - name: "Установка Docker-compose"
      block:

        - name: Install pip
          apt:
            name:
              - python3-venv
              - python3-pip
            update_cache: yes

        - name: Install docker-compose
          pip:
            name: docker-compose
      become: yes

    - name: "Завершение установки"
      block:
        - name: "Add group"
          ansible.builtin.group:
            name: docker
            state: present

        - name: "Add user"
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            comment: Ilya
            groups: docker
            append: yes

        - name: "Unconditionally reboot the machine with all defaults"
          reboot:
      become: yes


